app_job_retrieve:
    path:   /api/v1/job/{id}
    methods: [GET]
    defaults:
        _controller: AppBundle:Job:retrieve

app_job_create:
    path:   /api/v1/job
    methods: [POST]
    defaults:
        _controller: AppBundle:Job:create
