services:
    app.manager.worker:
        class: AppBundle\Manager\WorkerManager
        arguments:
            - @app.document.repository.worker
            - @app.document.repository.job
    app.manager.job:
        class: AppBundle\Manager\JobManager
        arguments:
            - @app.document.repository.job
    app.manager.job_description:
        class: AppBundle\Manager\JobDescriptionManager
        arguments:
            - @app.document.repository.job_description