services:
    app.guzzle.client:
        class: GuzzleHttp\Client
    app.transport.job:
        class: AppBundle\Transport\JobTransport
        arguments:
            - @app.guzzle.client
    app.manager.worker:
        class: AppBundle\Manager\WorkerManager
        arguments:
            - @app.document.repository.worker
            - @app.document.repository.job
    app.manager.job:
        class: AppBundle\Manager\JobManager
        arguments:
            - @app.document.repository.job
            - @app.manager.worker
            - @app.transport.job
    app.manager.job_description:
        class: AppBundle\Manager\JobDescriptionManager
        arguments:
            - @app.document.repository.job_description