AppBundle\Document\Job:
    repositoryClass: AppBundle\Document\Repository\JobRepository
    fields:
        id:
            id:  true
        job:
            type: string
        status:
            type: string
        parameters:
            type: raw
        result:
            type: raw
        workerId:
            type: string
