AppBundle\Document\JobDescription:
    repositoryClass: AppBundle\Document\Repository\JobDescriptionRepository
    fields:
        id:
            id:  true
            type:  string
        requirements:
            type: collection